version: "3"

networks:
  stack_ponte:
    external: true

services:
  apacheoal:
    container_name: "apachedinalweb"
    image: webdevops/apache
    networks:
      - stack_ponte
    restart: always
    ports:
      - 852:80
    volumes:
      - "${PATHPESSOAL}/dinal-web/front:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sitedinal.rule=Host(`dinal.${DOMAIN}`,
        `dinal.com`, `www.dinal.com`)"
      - "traefik.http.services.sitedinal.loadbalancer.server.port=80"
